name: Terraform CI/CD

on:
    push:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest
        outputs:
            ecr_uri: ${{ steps.get_ecr_uri.outputs.ecr_uri }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.12.2
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Import ECR if exists
              run: |
                if aws ecr describe-repositories --repository-names iacredmine --region ap-northeast-1; then
                    echo "Repository exists, importing to Terraform state..."
                    terraform import aws_ecr_repository.redmine iacredmine
                else
                    echo "Repository does not exists, will be created by apply"
                fi

            - name: Terraform Plan
              run: terraform plan

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve

            - name: Get ECR URI
              id: get_ecr_uri
              run: echo "ecr_uri=$(terraform output -raw ecr_repository_uri)" >> $GITHUB_OUTPUT

    docker:
        runs-on: ubuntu-latest
        needs: terraform

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-1

            - name: Debug ECR URI
              run: |
                echo "ECR URI: ${{ needs.terraform.outputs.ecr_uri }}"

            - name: Login to ECR
              run: |
                aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ needs.terraform.outputs.ecr_uri }}

            - name: Build Docker image
              run: docker build -t iacredmine .

            - name: Tag and Push Docker image
              run: |
                docker tag iacredmine:latest ${{ needs.terraform.outputs.ecr_uri }}:latest
                docker push ${{ needs.terraform.outputs.ecr_uri }}:latest